### ISSUE TITLE
npm run start with error

### ISSUE THREAD

**Issue by jackyjqcheung** [worldsibu/convector-example-drug-supply-chain#15]
npm run start 
at the project folder, it failed to create the ch1_drug database
In the coudb webpage , http://localhost:5084/_utils/#
only ch1_ and ch1_lscc database exists, any idea?

Here is the error log.

[hurley] - installing smart contract located at /home/osboxes/fabric/convector/drugChain/chaincode-drug
Installing Chaincode drug version 1.0 at org1
2019-09-05 10:24:58.147 CST [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-09-05 10:24:58.147 CST [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-09-05 10:24:58.186 CST [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" > 
Installed Chaincode drug version 1.0 at org1
Installing Chaincode drug version 1.0 at org2
2019-09-05 10:24:58.240 CST [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-09-05 10:24:58.241 CST [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-09-05 10:24:58.278 CST [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" > 
Installed Chaincode drug version 1.0 at org2
Instantiating Chaincode at org1
It may take a few minutes depending on the chaincode dependencies
2019-09-05 10:25:08.341 CST [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-09-05 10:25:08.341 CST [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Instantiated Chaincode at org1

> @worldsibu/convector-example-drug-supply-chain@2.0.0 cc:initialInvoke /home/osboxes/fabric/convector/drugChain
> hurl invoke drug participant_get "user1"

[hurley] - user1
[hurley] - Sending transaction as user1 in org org1...
[hurley] - At least one peer returned an error!
[hurley] - This may happen when a transaction queries private data that's not accessible to all peers
(node:6432) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at /home/osboxes/fabric/convector/drugChain/node_modules/@worldsibu/hurley/dist/generators/invokechaincode.sh.js:70:75
    at Array.map (<anonymous>)
    at InvokeChaincodeShGenerator.<anonymous> (/home/osboxes/fabric/convector/drugChain/node_modules/@worldsibu/hurley/dist/generators/invokechaincode.sh.js:69:44)
    at step (/home/osboxes/fabric/convector/drugChain/node_modules/tslib/tslib.js:133:27)
    at Object.throw (/home/osboxes/fabric/convector/drugChain/node_modules/tslib/tslib.js:114:57)
    at rejected (/home/osboxes/fabric/convector/drugChain/node_modules/tslib/tslib.js:105:69)
    at <anonymous>
(node:6432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> @worldsibu/convector-example-drug-supply-chain@2.0.0 vw:install /home/osboxes/fabric/convector/drugChain
> ./@worldsibu/views/installViews.sh

{"error":"not_found","reason":"Database does not exist."}
{"error":"not_found","reason":"Database does not exist."}
{"error":"not_found","reason":"Database does not exist."}
{"error":"not_found","reason":"Database does not exist."}
{"error":"not_found","reason":"Database does not exist."}
{"error":"not_found","reason":"Database does not exist."}

**Comment by tianlu102238612** [comment]
I got the same error, have you fixed it?
